version: '3'
services:
    h1:
        image: scapy
        container_name: h1
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh host 1
        networks:
            h1_net:
                ipv4_address: 10.1.1.3
        volumes:
        - ../:/home/p4/pot
    ingressNode:
        image: p4custom-java
        container_name: ingressNode
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh 11
        networks:
            h1_net:
                ipv4_address: 10.1.1.2
            ingress_net:
                ipv4_address: 10.0.1.3
            controller:
                ipv4_address: 10.0.0.11
        volumes:
        - ../:/home/p4/pot
    egressNode:
        image: p4custom-java
        container_name: egressNode
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh 20
        networks:
            zegress_net:
                ipv4_address: 10.0.9.2
            zh2_net:
                ipv4_address: 10.1.2.2
            controller:
                ipv4_address: 10.0.0.20
        volumes:
        - ../:/home/p4/pot
    h2:
        image: scapy
        container_name: h2
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh host 2
        networks:
            zh2_net:
                ipv4_address: 10.1.2.3
        volumes:
        - ../:/home/p4/pot
    controller:
        image: p4custom-java
        container_name: controller
        cap_add:
        - NET_ADMIN
        privileged: true
        command:  /home/p4/pot/docker/run.sh controller 10
        networks:
            controller:
                ipv4_address: 10.0.0.10
            kafka-net:
                ipv4_address: 10.2.1.10
        volumes:
        - ../:/home/p4/pot
    middleNode1:
        image: p4custom-java
        container_name: middleNode1
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh 12
        networks:
            ingress_net:
                ipv4_address: 10.0.1.2
            middle1_middle2_net:
                ipv4_address: 10.0.2.3
            controller:
                ipv4_address: 10.0.0.12
        volumes:
        - ../:/home/p4/pot
    middleNode2:
        image: p4custom-java
        container_name: middleNode2
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh 13
        networks:
            middle1_middle2_net:
                ipv4_address: 10.0.2.2
            middle2_middle3_net:
                ipv4_address: 10.0.3.3
            controller:
                ipv4_address: 10.0.0.13
        volumes:
        - ../:/home/p4/pot
    middleNode3:
        image: p4custom-java
        container_name: middleNode3
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh 14
        networks:
            middle2_middle3_net:
                ipv4_address: 10.0.3.2
            middle3_middle4_net:
                ipv4_address: 10.0.4.3
            controller:
                ipv4_address: 10.0.0.14
        volumes:
        - ../:/home/p4/pot
    middleNode4:
        image: p4custom-java
        container_name: middleNode4
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh 15
        networks:
            middle3_middle4_net:
                ipv4_address: 10.0.4.2
            middle4_middle5_net:
                ipv4_address: 10.0.5.3
            controller:
                ipv4_address: 10.0.0.15
        volumes:
        - ../:/home/p4/pot
    middleNode5:
        image: p4custom-java
        container_name: middleNode5
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh 16
        networks:
            middle4_middle5_net:
                ipv4_address: 10.0.5.2
            middle5_middle6_net:
                ipv4_address: 10.0.6.3
            controller:
                ipv4_address: 10.0.0.16
        volumes:
        - ../:/home/p4/pot
    middleNode6:
        image: p4custom-java
        container_name: middleNode6
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh 17
        networks:
            middle5_middle6_net:
                ipv4_address: 10.0.6.2
            middle6_middle7_net:
                ipv4_address: 10.0.7.3
            controller:
                ipv4_address: 10.0.0.17
        volumes:
        - ../:/home/p4/pot
    middleNode7:
        image: p4custom-java
        container_name: middleNode7
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh 18
        networks:
            middle6_middle7_net:
                ipv4_address: 10.0.7.2
            middle7_middle8_net:
                ipv4_address: 10.0.8.3
            controller:
                ipv4_address: 10.0.0.18
        volumes:
        - ../:/home/p4/pot
    middleNode8:
        image: p4custom-java
        container_name: middleNode8
        cap_add:
        - NET_ADMIN
        privileged: true
        command: /home/p4/pot/docker/run.sh 19
        networks:
            middle7_middle8_net:
                ipv4_address: 10.0.8.2
            zegress_net:
                ipv4_address: 10.0.9.3
            controller:
                ipv4_address: 10.0.0.19
        volumes:
        - ../:/home/p4/pot
networks:
    h1_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.1.1.0/24
    ingress_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.1.0/24
    zegress_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.9.0/24
    zh2_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.1.2.0/24
    controller:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24
    kafka-net:
        external: true
    middle1_middle2_net:
        driver: bridge
        ipam: 
            driver: default
            config:
                - subnet: 10.0.2.0/24
    middle2_middle3_net:
        driver: bridge
        ipam: 
            driver: default
            config:
                - subnet: 10.0.3.0/24
    middle3_middle4_net:
        driver: bridge
        ipam: 
            driver: default
            config:
                - subnet: 10.0.4.0/24
    middle4_middle5_net:
        driver: bridge
        ipam: 
            driver: default
            config:
                - subnet: 10.0.5.0/24
    middle5_middle6_net:
        driver: bridge
        ipam: 
            driver: default
            config:
                - subnet: 10.0.6.0/24
    middle6_middle7_net:
        driver: bridge
        ipam: 
            driver: default
            config:
                - subnet: 10.0.7.0/24
    middle7_middle8_net:
        driver: bridge
        ipam: 
            driver: default
            config:
                - subnet: 10.0.8.0/24
